name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            targets: x86_64-unknown-linux-gnu
          - os: windows-latest
            targets: x86_64-pc-windows-msvc
          - os: macos-latest
            targets: x86_64-apple-darwin,aarch64-apple-darwin

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Setup Node.js
      uses: actions/setup-node@v4.1.0
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'scripts/package-lock.json'
        run: cd scripts && npm install && cd ..

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.targets }}

    - name: Install Linux dependencies (x86_64)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          protobuf-compiler \
          pkg-config \
          libssl-dev \
          openssl \
          musl-tools \
          musl-dev \
          libssl-dev:native \
          linux-libc-dev:native

        # 设置 OpenSSL 环境变量
        echo "OPENSSL_DIR=/usr" >> $GITHUB_ENV
        echo "OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
        echo "OPENSSL_INCLUDE_DIR=/usr/include/openssl" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV

    - name: Build Linux x86_64 (Dynamic)
      if: runner.os == 'Linux'
      run: bash scripts/build.sh

    - name: Build Linux x86_64 (Static)
      if: runner.os == 'Linux'
      run: |
        # 使用 musl 目标
        rustup target remove x86_64-unknown-linux-gnu
        rustup target add x86_64-unknown-linux-musl

        # 设置静态编译环境变量
        export CC=musl-gcc

        bash scripts/build.sh --static

    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      run: |
        brew install \
          protobuf \
          pkg-config \
          openssl@3
        echo "OPENSSL_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$(brew --prefix openssl@3)/lib/pkgconfig" >> $GITHUB_ENV

    - name: Install Windows dependencies
      if: runner.os == 'Windows'
      run: |
        choco install -y protoc
        choco install -y openssl
        choco install -y nodejs-lts

        # 刷新环境变量
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")

        # 设置 OpenSSL 环境变量
        echo "OPENSSL_DIR=C:\Program Files\OpenSSL" >> $env:GITHUB_ENV
        echo "PKG_CONFIG_PATH=C:\Program Files\OpenSSL\lib\pkgconfig" >> $env:GITHUB_ENV

    - name: Build macOS (Dynamic)
      if: runner.os == 'macOS' || runner.os == 'Windows'
      run: bash scripts/build.sh

    - name: Build macOS (Static)
      if: runner.os == 'macOS' || runner.os == 'Windows'
      run: bash scripts/build.sh --static

    # - name: Verify build artifacts
    #   run: |
    #     if [ ! -d "release" ] || [ -z "$(ls -A release)" ]; then
    #       echo "Error: No build artifacts found in release directory"
    #       exit 1
    #     fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4.5.0
      with:
        name: binaries-${{ matrix.os }}
        path: release/*
        retention-days: 1

  build-freebsd:
    name: Build FreeBSD
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Build on FreeBSD
      uses: vmactions/freebsd-vm@v1.1.5
      with:
        usesh: true
        prepare: |
          # 设置持久化的环境变量
          echo 'export SSL_CERT_FILE=/etc/ssl/cert.pem' >> /root/.profile
          echo 'export PATH="/usr/local/bin:$PATH"' >> /root/.profile

          # 安装基础依赖
          pkg update
          pkg install -y \
            git \
            curl \
            node20 \
            www/npm \
            protobuf \
            ca_root_nss \
            bash \
            gmake \
            pkgconf \
            openssl \
            libressl-devel \
            libiconv \
            gettext-tools \
            gettext-runtime

          export SSL_CERT_FILE=/etc/ssl/cert.pem

          # 克隆代码（确保在正确的目录）
          cd /root
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY .

          # 安装 rustup 和 Rust
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain nightly

          # 设置持久化的 Rust 环境变量
          echo '. "$HOME/.cargo/env"' >> /root/.profile

          # 添加所需的目标支持
          . /root/.profile
          rustup target add x86_64-unknown-freebsd
          rustup component add rust-src

        run: |
          # 加载环境变量
          . /root/.profile

          echo "构建动态链接版本..."
          /usr/local/bin/bash scripts/build.sh

          echo "构建静态链接版本..."
          /usr/local/bin/bash scripts/build.sh --static

    - name: Upload artifacts
      uses: actions/upload-artifact@v4.5.0
      with:
        name: binaries-freebsd
        path: release/*
        retention-days: 1

  release:
    # 创建 GitHub Release 的任务
    name: Create Release
    # 需要等待 build 和 build-freebsd 任务完成才能执行
    needs: [build, build-freebsd]
    # 在 Ubuntu 最新版本上运行
    runs-on: ubuntu-latest
    # 授予写入代码库内容的权限，用于创建 Release
    permissions:
      contents: write

    steps:
    # 第1步：检出代码仓库
    - uses: actions/checkout@v4.2.2

    # 第2步：下载之前任务上传的所有构建产物
    - name: Download all artifacts
      uses: actions/download-artifact@v4.1.8
      with:
        path: artifacts  # 下载到 artifacts 目录

    # 第3步：准备发布资产
    - name: Prepare release assets
      run: |
        # 创建 release 目录用于存放最终要发布的文件
        mkdir -p release
        cd artifacts
        # 遍历所有 binaries-* 目录，将内容复制到 release 目录
        for dir in binaries-*; do
          cp -r "$dir"/* ../release/
        done

    # 第4步：检查文件大小和列表（用于调试）
    - name: Check file sizes and list
      run: |
        echo "======= 文件列表及大小 ======="
        find release -type f -exec ls -la {} \;
        echo "======= 文件大小统计 ======="
        find release -type f -exec du -h {} \;
        echo "======= 总大小统计 ======="
        du -sh release/

    # 第5步：压缩大文件（超过50MB的文件）
    - name: Compress large files
      run: |
        cd release
        # 查找并压缩大文件 (大于50MB)
        find . -type f -size +50M | while read file; do
          echo "压缩大文件: $file"
          gzip -9 "$file"
        done

    # 第6步：生成校验和文件
    - name: Generate checksums
      run: |
        cd release
        # 为所有文件生成 SHA256 校验和，保存到 SHA256SUMS.txt
        sha256sum * > SHA256SUMS.txt

    # 第7步：创建 GitHub Release 并上传文件
    - name: Create Release
      uses: softprops/action-gh-release@v2.2.0
      with:
        # 指定要上传的文件（采用绝对路径）
        files: ${{ github.workspace }}/release/*
        # 是否创建为草稿，false 表示直接发布
        draft: false
        # 是否标记为预发布版本
        prerelease: false
        # 自动生成发布说明
        generate_release_notes: true
        # 如果指定的文件不存在则不会失败
        fail_on_unmatched_files: false
